openapi: 3.0.0
servers:
   - url: https://api.open-meteo.com
info:
   title: Open-Meteo APIs
   description: "Provides current weather conditions."
   version: "1.0"
   contact:
      name: Open-Meteo
      url: https://open-meteo.com
      email: info@open-meteo.com
   license:
      name: Attribution 4.0 International (CC BY 4.0)
      url: https://creativecommons.org/licenses/by/4.0/
   termsOfService: https://open-meteo.com/en/features#terms
paths:
   /v1/forecast:
      get:
         operationId: forecast
         tags:
            - Weather Forecast APIs
         summary: current weather for coordinates
         description: Weather information for given WGS84 latitude and longitude coordinates.
         parameters:
            - name: latitude
              in: query
              required: true
              description: "WGS84 coordinate"
              schema:
                 type: number
                 format: double
            - name: longitude
              in: query
              required: true
              description: "WGS84 coordinate"
              schema:
                 type: number
                 format: double
            - name: current_weather
              in: query
              required: true
              schema:
                 type: boolean
                 default: true
         responses:
            "200":
               description: OK
               content:
                  application/json:
                     schema:
                        type: object
                        properties:
                           latitude:
                              type: number
                              example: 52.52
                              description: WGS84 of the center of the weather grid-cell which was used to generate this forecast. This coordinate might be up to 5 km away.
                           longitude:
                              type: number
                              example: 13.419.52
                              description: WGS84 of the center of the weather grid-cell which was used to generate this forecast. This coordinate might be up to 5 km away.
                           elevation:
                              type: number
                              example: 44.812
                              description: The elevation in meters of the selected weather grid-cell. In mountain terrain it might differ from the location you would expect.
                           generationtime_ms:
                              type: number
                              example: 2.2119
                              description: Generation time of the weather forecast in milli seconds. This is mainly used for performance monitoring and improvements.
                           utc_offset_seconds:
                              type: integer
                              example: 3600
                              description: Applied timezone offset from the &timezone= parameter.
                           current_weather:
                              $ref: "#/components/schemas/CurrentWeather"
            "400":
               description: Bad Request
               content:
                  application/json:
                     schema:
                        type: object
                        properties:
                           error:
                              type: boolean
                              description: Always set true for errors
                           reason:
                              type: string
                              description: Description of the error
                              example: "Latitude must be in range of -90 to 90°. Given: 300"
components:
   schemas:
      CurrentWeather:
         type: object
         description: "Current weather conditions with the attributes: time, temperature, wind_speed, wind_direction and weather_code"
         properties:
            time:
               type: string
            temperature:
               type: number
            wind_speed:
               type: number
            wind_direction:
               type: number
            weather_code:
               type: integer
         required:
            - time
            - temperature
            - wind_speed
            - wind_direction
            - weather_code
